#pragma once

#include <GLAD/glad.h>
#include <GLFW/glfw3.h>

enum REKey
{
	REKEY_MOUSE_LEFT	= GLFW_MOUSE_BUTTON_LEFT,
	REKEY_MOUSE_RIGHT	= GLFW_MOUSE_BUTTON_RIGHT,
	REKEY_KEY_W			= GLFW_KEY_W,
	REKEY_KEY_A			= GLFW_KEY_A,
	REKEY_KEY_S			= GLFW_KEY_S,
	REKEY_KEY_D			= GLFW_KEY_D,
};